### ISSUE TITLE
invalid meta messages when installing Bower bi-app-sass package

### ISSUE THREAD

**Issue by talbs** [anasnakawa/bi-app-sass#12]
Hi! Firstly, thanks so much for this great tool. We've used it extensively throughout our edX and Open edX UI to support a lot of our international learners. Its been super easy to use and work with (even alongside multiple grid/layout tools).

---

We're currently designing/developing a UI and front end pattern library for a lot of our apps to use. When leveraging Bower for this library's third party dependencies (including bi-app-sass), we recently ran into the following error when locally running `bower install`:

```
$ bower install

...

bower bi-app-sass#*              invalid-meta bi-app-sass is missing "main" entry in bower.json
bower bi-app-sass#*              invalid-meta bi-app-sass is missing "ignore" entry in bower.json
bower bi-app-sass#*              resolved git://github.com/anasnakawa/bi-app-sass.git#ee88ef8ebb
```

We're using the current version of the package. Let me know if there's anything else I can do to help or if this is simply a case of designer user error :stuck_out_tongue:

**Comment by anasnakawa** [comment]
sorry for the late response,
those messages from bower are just warning, you should be able to use `bi-app-sass` with no issues,

but you are correct, I should update those meta data in bower package file, 
beside that, is there anything issues that `bi-app-sass` is causing ?

**Comment by talbs** [comment]
@anasnakawa, apologies on my end for the radio silence. Yeah, we've been using ``bi-app-sass`` with those warnings in place. If you're comfortable with it, I can even get a starter PR to get that metadata in place. Let me know.

- - -

There is another issue we're hitting with the bower package for ``bi-app-sass`` currently. I'll make a new issue as its a little different.

**Comment by talbs** [comment]
For reference, here's the other Bower-related issue: https://github.com/anasnakawa/bi-app-sass/issues/15
