### ISSUE TITLE
Bower no longer using a package's bower.json version

### ISSUE THREAD

**Issue by talbs** [anasnakawa/bi-app-sass#15]
Hi, apologies for the issue spam. 

We've come across an issue with the more recent versions of bower (~1.6.5) where the version number set in a package's ``bower.json`` file isn't used when installing/referencing that package. We hit this when trying to set a specific version on ``bi-app-sass`` (see https://github.com/edx/ux-pattern-library/pull/223).

Here's the output from our repo's ``bower.json`` file ():
```
...
"dependencies": {
    "animate.css": "~3.3.0",
    "bi-app-sass": "~1.1.0",
    "bourbon": "~4.2.3",
    "breakpoint-sass": "~2.6.1",
    "requirejs": "~2.1.15",
    "susy": "~2.2.5"
  }
...
```

With that in mind, here's the output when I try to run ``bower install`` with v1.6.5:
```
$ bower install

bower bi-app-sass#~1.1.0    not-cached git://github.com/anasnakawa/bi-app-sass.git#~1.1.0
bower bi-app-sass#~1.1.0       resolve git://github.com/anasnakawa/bi-app-sass.git#~1.1.0
bower bi-app-sass#~1.1.0  ENORESTARGET No tag found that was able to satisfy ~1.1.0

Additional error details:
No versions found in git://github.com/anasnakawa/bi-app-sass.git
```

- - - 

We came across this with our Bower package recently and found that Bower now obtains and manages versions by git tags/releases. We created our first release on Github with a corresponding version number (https://github.com/edx/ux-pattern-library/releases) and our package was able to be used externally again with the ``bower install`` command.

The same approach might be what ``bi-app-sass`` needs to migrate to.

- - -

Let me know if you need any more info or if there's something I can do to help.

**Comment by anasnakawa** [comment]
If I got this right, mainly the issue happened with bower because the version mentioned in `bi-app-sass` is set to `1.1.0`, and this tag is not available in the repository, right ?

if that's the case, I have just created a new tag & updated `npm` registry as well.

**Comment by talbs** [comment]
@anasnakawa, yep! That's it. Apologies for my long way around the problem. I can verify that Bower now has the up-to-date package registered - http://bower.io/search/?q=bi-app-sass.

Thanks much!
